### ISSUE TITLE
feature: cmd-line login

### ISSUE THREAD

**Issue by nikolajbrinch** [fydrah/loginapp#10]
It would really help us, if loginapp could potentially be used as a service, where the token etc. can be gotten from the command line, and not via the browser. We are in a situation, where this usage pops up several times.
As a web browser is mandatory for Open ID Connect, as far as I read the spec. I was wondering if it would be possible to use ie. Chrome headless in a sidecar, to do the actual login, and then grab the response, and feed it back to the caller.

The reason I suggest this as a loginapp improvement/feature request is that I think it would be a nice improvent of loginapp.
As I am not a Go coder (JVM, Python and C/C++ etc.) I can't really improve on loginapp, but I think that is where it belongs. I could go for doing a Python or Java (using ie. Selenium as a PoC), but that really wouldn't help improve loginapp.

**Comment by fydrah** [comment]
Hi @nikolajbrinch ,

Yes this could be a great feature, unfortunately I currently don't know (and didn't search) how to implement this.
If you have ideas, I'll be glade to discuss design of the feature with you.

I'll start to work on this on the following days.

Regards,

**Comment by nikolajbrinch** [comment]
Well if I were to do it, with my background as Java backend developer, I would do a small micronaut service in a sidecar, that would use something like selenium to instrument a headless chrome in the same sidecar, to emulate the client.
But it can probably be done in another way that is done using Go, but I really wouldn’t know how.
I can take a stab at trying to do that and then you can maybe review and fill in the blanks?

**Comment by nikolajbrinch** [comment]
Oh, in that way you can HTTPS POST the the service to get token information (login). Then curl would be everybody’s best friend.

**Comment by fydrah** [comment]
Based on what you said (if I understood what you want to do :p), the auth process will be managed by the server side with the following workflow:
* **client** run an cli authentication, ex: `loginapp auth https://loginapp.example.org -u john -p password`
* loginapp **server** handles requests:
  * manage a sidecar container (with selenium for example):
    * opens a browser
    * fulfill user/password fields
    * get response from dex
  * format output for the user
* **client** print output or add auth information into kubeconfig

Is that right ?

And of course, if you have ideas to draft a first version, I will be happy to help you improve it :)

---

Also, I started to look at some golang libraries we could used. I found [chromedp](https://github.com/chromedp/chromedp) that may suit to our needs.
It does not need an additional dependency like selenium to drive a headless browser.

I'm currently testing it, to understand how it works, and if it looks like a good solution. I'll give you updates

**Comment by nikolajbrinch** [comment]
I think that is what we need. No Selenium isn't needed, if we can do it in Go. I just have a long history with Java, and knows what tools (WebDriver) that can be used from that angle.
It could probably also be done from JS with all the libraries for this type of stuff (Jasmine, PhantomJS etc).

**Comment by fydrah** [comment]
I had successful test results with chromedp:
```
2018/11/06 09:59:07 -> {"method":"DOM.setChildNodes","params":{"parentId":86,"nodes":[{"nodeId":87,"parentId":86,"backendNodeId":817,"nodeType":1,"nodeName":"CODE","localName":"code","nodeValue":"","childNodeCount":1,"children":[{"nodeId":88,"parentId":87,"backendNodeId":818,"nodeType":3,"nodeName":"#text","localName":"","nodeValue":"- name: admin\n  user:\n    auth-provider:\n      config:\n        idp-issuer-url: http://dex.example.com:5556\n        client-id: loginapp\n        id-token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjRlNTJhZmM0MDViZmJmYzMxZGUwODYyZjVlYWQ0MTdjNjU5MTUxYjkifQ.eyJpc3MiOiJodHRwOi8vZGV4LmV4YW1wbGUuY29tOjU1NTYiLCJzdWIiOiJDaVF3T0dFNE5qZzBZaTFrWWpnNExUUmlOek10T1RCaE9TMHpZMlF4TmpZeFpqVTBOallTQld4dlkyRnMiLCJhdWQiOiJsb2dpbmFwcCIsImV4cCI6MTU0MTU4MTE0NywiaWF0IjoxNTQxNDk0NzQ3LCJhdF9oYXNoIjoielJpZUdzV3JNeFBrWWZFTzYtd1pOZyIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6ImFkbWluIn0.VVnkCfpFBQRQKBacdnyrNSxmTr18E2KaDFGJ2uel-m0-mAu6TTc6iGWaRuw2yC9oed3WSBKunBf8z8DyoD7Qo7hv8Ec1fz43Ae1TyKU_96FFjlQkv6JiYb5YuOqZgn9XCevhR2B1A-KAwnNVGRjYaVh4dFL3H0UENfADCc6strjDPrpRVq8103iczYjq-hS-rs0aZHv8aM9pKPvZ_Q76QRKBktzFPeymH08gjoscDHkPv6opTKG6bjdyt6bEpfrc1UwmzEDOKROmZ8C-cJbTzSaNlSos9oTlBAQsAWLUDasQvKbYWX7PwRYUAKg7_BVJipAYY21tJPCk833S5ruvwQ\n        client-secret: ZXhhbXBsZS1hcHAtc2VjcmV0\n        refresh-token: ChlidWN3NHF2bW1jZmVrZjRiZHQycm9sNDd2EhlscmJjbjN6bHZ2NG5kaHpqNTMydnc2cm5h\n      name: oidc"}],"attributes":["class"," language-yaml","id","kubeconfig"]}]}}
```
(as you can see we retrieve the output of the token).

I think this could be the solution

**Comment by nikolajbrinch** [comment]
That sounds really nice! Great work.

Could client be curl? What I think is that simple HTTP(S) would be a nice client for this, so one could contact loginapp, that would do the login and send back the JSON.

**Comment by fydrah** [comment]
I think that it could be a new endpoint on loginapp API, so yes you could retrieve token with a curl

**Comment by dmolik** [comment]
Is the current plan to target a kubectl plugin?

**Comment by fydrah** [comment]
I have not given any news for a long time on this issue..

My first solution does not seem to be the good way:
* poor resilience: I had too much issues with chromedp due to random parsing failures
* performance issues:  waiting for the local chrome browser to launch, timeouts during queries..

This is not enough stable to base a cli tool on it.

An other approach of loginapp could be:
1. (implemented) Loginapp as remote web app, centralized for everybody (= like it currently works)
1. (not implemented yet) Loginapp as a kubectl plugin:
    * Run `kubectl login` (for example)
    * Prompt a new page on your browser, you login on your idp, idp redirects on your local loginapp browser page
    * Loginapp parse data and save it into kubeconfig file.

This 2nd implementation brings some inconveniences...:
* you need to issue certificates for each client
* this is not a fully automated process, because of OIDC nature to be entirely browser based

...and some advantage:
* no more needs of a centralized loginapp
* improve security by the usage of [public clients](https://github.com/dexidp/dex/blob/master/Documentation/custom-scopes-claims-clients.md#public-clients)

I currently do not have much time to implement 2nd opt. If I do have time, I prefer to work on documentation first, because there is clearly no real documentation at all :) And then try an implementation of this feature.

Of course, if you have any suggestion about the implementation, or if you want to help, I will be enjoy to discuss about it with you.

**Comment by jetersen** [comment]
@fydrah hmm just discovered: https://github.com/int128/kubelogin
Perhaps we could combine the two of them?
As loginapp is useful for sharing kubeconfig.

**Comment by fydrah** [comment]
hi @jetersen

yes you're right, no need to develop another cli tool since this one exists and is still under active development (and i cant do a cli tool as good as they've done :p )

I will add a note on documentation on how to configure loginapp & dex to work with (kubelogin)[https://github.com/int128/kubelogin], and maybe add an other panel on loginapp frontend to easily configure kubelogin (kubeconfig part with issuer_url, secret, and extra scopes such as groups and email)

**Comment by jetersen** [comment]
perhaps a config flag to include the kubelogin in the full output?

**Comment by jetersen** [comment]
I think we will switch kubelogin as it just works. Though we are still discussing if login app is needed as a sharing platform for the kube config.
Atm we use both loginapp and kubelogin due to not having switched entirely.

This is how we have dex configured for shared login duty between loginapp and kubelogin
```
          staticClients:
          - id: loginapp
            redirectURIs:
            - 'https://login.company.io/callback'
            - 'http://localhost:8000'
            - 'http://localhost:18000'
            name: 'Loginapp'
            secret: ****
```

We than have this in our kube config:

```
users:
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --oidc-issuer-url=https://dex.company.io/dex
      - --oidc-client-id=loginapp
      - --oidc-client-secret=****
      - --oidc-extra-scope=profile
      - --oidc-extra-scope=email
      - --oidc-extra-scope=groups
      command: kubelogin
```

We use `kubelogin` on `PATH` as Lensapp is bundling their kubectl where it does not work with krew.

For Windows users on WSL you might be interested in some "hacks"

This works for github cli `gh`
```
export BROWSER="wslview"
```

for kubelogin which does not read `BROWSER` env (PR inc), you can create an `xdg-open` shell script with the following and make the script executable and put it on `PATH`:
```sh
#!/bin/sh
wslview "$@"
```
